### ISSUE TITLE
Feature Tracker

### ISSUE THREAD

**Issue by PeterMitrano** [WPISmartmouse/SmartmouseSim#1]
**Layout Window**
 - [ ] bottom bar with time, pause, reset
 - [ ] side tabs with info
 - [ ] draw maze and mouse

**Messaging & Logging**
 - [ ] Publish time, position, etc...
 - [ ] Subscribe to commands
 - [ ] Log special debug channel
 - [ ] All log messages go to log file & debug console
 - [ ] Do all GUI actions as messages

**Plugin Interface**
 - [ ] Create class 
 - [ ] plugin loading mechanism

**Tests**
 - [ ] gtest unit tests

**Documentation/User Guide**
 - [ ] Doxygen
 - [ ] User Guide (Github Wiki)
